import React from 'react';
import styles from './page.module.css';

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by pamela',
};

const Dashboard = () => {
  return <div>Dashboard</div>;
};

export default Dashboard;
